### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException Wrong thread

### ISSUE THREAD

**Issue by arifur-nureca** [voximplant/android-sdk-kotlin-demo#17]
Getting the following Crash:
```

org.webrtc.Camera1Session.checkIsOnCameraThread (Camera1Session.java:367)
org.webrtc.Camera1Session.stop (Camera1Session.java:200)
org.webrtc.CameraCapturer$6.run (CameraCapturer.java:315)
android.os.Handler.handleCallback (Handler.java:883)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:214)
android.os.HandlerThread.run (HandlerThread.java:67)
```

Please help in fixing this

**Comment by jedi1150** [comment]
Hello @arifur-nureca,

Could you send the full logcat?

**Comment by jedi1150** [comment]
Hello @arifur-nureca,

Please provide the following information: Voximplant SDK version, device model, Android version on the device.
The crash stack points that the crash happened on the camera stop. Could you please let me know what action from the application side caused this error (call end, stop sending video, switch camera or somehing else)?
Also please enable debug logging in ClientConfig() `enableDebugLogging = true`, make a call and attach the logcat logs from the beginning of the call to the error.

**Comment by arifur-nureca** [comment]
Hi @jedi1150,
I got this crash reported from Sentry. 
```
java.lang.IllegalStateException: Wrong thread
    at org.webrtc.Camera1Session.checkIsOnCameraThread(Camera1Session.java:367)
    at org.webrtc.Camera1Session.stop(Camera1Session.java:200)
    at org.webrtc.CameraCapturer$6.run(CameraCapturer.java:315)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.os.HandlerThread.run(HandlerThread.java:67)
```
Above is the stacktrace for it. I had enabled debugging, Once I am able to reproduce i will update here again.
