### ISSUE TITLE
Reconnecting after network connection problems

### ISSUE THREAD

**Issue by RuslanMusin** [voximplant/android-sdk-kotlin-demo#2]
I had been searching about how to reconnect a call after network was disconnected.
In my example (based on the issue, but I didn't find an answer to my question
https://github.com/voximplant/react-native-voximplant/issues/79) 
1) Start a call between two users (A & B)
2) Turn off internet for one of the users (B)
3) "B" will immediately fire a call ended event (onCallDisconnected)
4) "A" will continue to show that it's on a call for 30 seconds before disconnecting. 

What I want: When B turns on Internet before A is disconnected (<30 seconds) it will connect to the previous call with A. 
But in the demo, when B turns on Internet again, nothing happens. A is still connected with B, but B cannot reconnect to a previous call.
Is this possible to reconnect? And if it's possible how to do this?

**Comment by YuliaGrigorieva** [comment]
Hello @RuslanMusin,

It is possible to reconnect the call only if you use [VoxEngine.callUser](https://voximplant.com/docs/references/voxengine/voxengine/calluser) API in your VoxEngine scenario, i.e. the call is not in peer-to-peer mode.

If it is your case, it is required to make changes in your VoxEngine scenario and your application code.
This is a brief summary of the required steps:
1. When the call is established, JS scenario should send the URL that should be used to reconnect the call after internet connection is restored.
2. It is required to re-connect to the Voximplant Cloud and re-login on the application side when the internet connection is restored.
3. After successful login it is required to make HTTP request on previously received URL (and add id=<call_id> parameter)
4. The application will receive the incoming call with the following parameters. These 2 parameters allow to identify "the reconnect call" and handle it differently from general incoming call on your application.
-- "X-ID" in headers
-- from "reconnect" user 
5. It is required to answer this call.

The media stream will be restored between call participants.

The VoxEngine scenario example:
```
require(Modules.PushService);

var inCall;
var inCallUser;
var outCall;
var outCallUser;
var accessURL;

VoxEngine.addEventListener(AppEvents.Started, function (e) {
    accessURL = e.accessURL;
});


VoxEngine.addEventListener(AppEvents.HttpRequest, function (e) {
  if (e.path.indexOf("method=reconnect") !== -1) {
    var id = e.path.substring(e.path.indexOf("&id=") + 4);
    if (e.path.indexOf("&call=incoming") !== -1) {
      Logger.write("reconnect to incoming call");
      var oldCall = inCall;
      inCall = VoxEngine.callUser(inCallUser, "reconnect", "", {"X-ID" : id}, true);
        if (oldCall !== null)
          oldCall.hangup();
        inCall.addEventListener(CallEvents.Connected, function(e) {
          VoxEngine.sendMediaBetween(inCall, outCall);
          VoxEngine.easyProcess(inCall,outCall);
        });
        inCall.addEventListener(CallEvents.Disconnected, handleDisconnected);
        inCall.addEventListener(CallEvents.Failed, VoxEngine.terminate);
    }
    else if (e.path.indexOf("&call=outgoing") !== -1) {
        Logger.write("reconnect to outgoing call");
        var oldCall = outCall;
        outCall = VoxEngine.callUser(outCallUser, "reconnect", "", {"X-ID" : id}, true);
        if (oldCall !== null)
          oldCall.hangup();
        outCall.addEventListener(CallEvents.Connected, function(e) {
          VoxEngine.sendMediaBetween(inCall, outCall);
        });
        outCall.addEventListener(CallEvents.Disconnected, handleDisconnected);
        outCall.addEventListener(CallEvents.Failed, VoxEngine.terminate);
    }
    return "";
  }
});

function handleDisconnected(e) {
  if (e.call == outCall)
    outCall = null;
  if (e.call == inCall)
    inCall = null;
  //setTimeout(function(e) {
    if (outCall === null || inCall === null)
       VoxEngine.terminate();
  //}, 60000);
}

function forwardCallToUser(username) {
  outCallUser = username;
  inCallUser = inCall.callerid();
  outCall = VoxEngine.callUser(outCallUser, inCall.callerid(), null, {}, true);
  outCall.addEventListener(CallEvents.Connected, function(e) {
    VoxEngine.sendMediaBetween(inCall, outCall);
    inCall.answer();
    e.call.sendInfo("text", accessURL + "?method=reconnect&call=outgoing");
    inCall.sendInfo("text", accessURL + "?method=reconnect&call=incoming");
  });
  
  outCall.addEventListener(CallEvents.Failed, VoxEngine.terminate);
  outCall.addEventListener(CallEvents.Disconnected, handleDisconnected);
}

VoxEngine.addEventListener(AppEvents.CallAlerting, function(e) {
  inCall = e.call;
  inCall.addEventListener(CallEvents.Disconnected, handleDisconnected);
 
  forwardCallToUser(e.destination);
});
```

Best regards,
Yulia Grigorieva

**Comment by RuslanMusin** [comment]
Thank you for the quick response. I'll try to use the solution above

**Comment by savely-krasovsky** [comment]
@YuliaGrigorieva I work with @RuslanMusin, but as backend-developer. Want to clarify something. In our case we use AndroidSDK only to get inbound calls, so as far as I got it, we do not use `VoxEngine.callUser` method.

So there is no way to implement reconnection in this case?

**Comment by YuliaGrigorieva** [comment]
Hello @L11R ,

What VoxEngine API do you use in your VoxEngine scenario?

To reconnect a call, the call media trafiic must go through Voximplant Servers. If you use [VoxEngine.callUserDirect](https://voximplant.com/docs/references/voxengine/voxengine/calluserdirect), it is not possible as the traffic goes in peer-to-peer mode. If you use any other API, it should be possible. 

Best regards,
Yulia Grigorieva

**Comment by savely-krasovsky** [comment]
@YuliaGrigorieva thanks for the answer. I got it, we had ready environment prepared by our voice team and didn't know about scenarios. Now it seems that we are using `callUser` method.

**Comment by YuliaGrigorieva** [comment]
Hello @L11R,

In this case you can take a look at my previous comment that describes how to implement reconnect functionality.

Please let me know if you have any questions.

Best regards,
Yulia Grigorieva
