### ISSUE TITLE
Cannot start from killed app

### ISSUE THREAD

**Issue by henriquetroiano** [voximplant/android-sdk-kotlin-demo#24]
Hello guys,

![image](https://user-images.githubusercontent.com/63327237/222240612-3d834d04-3ab7-4883-8a05-19b8ad60fb9f.png)

When this FirebasePushService receives a push, it calls the Shares.authService, but at this time, authService lateinit is not initialized yet.

This is the fresh app example.

Can you please tell me how can I make it work from killed app ?

**Comment by jedi1150** [comment]
Hello,
You can add a new property to the `Shared.kt`.
```
lateinit var authService: AuthService
val isAuthServiceInitialized: Boolean
    get() = ::authService.isInitialized
```
Then check and set the `authService` property before invoking `pushNotificationReceived()`.
```
override fun onMessageReceived(remoteMessage: RemoteMessage) {
    val push = remoteMessage.data
    if (push.containsKey("voximplant")) {
        if (!Shared.isAuthServiceInitialized) {
            Shared.authService = AuthService(
                Voximplant.getClientInstance(
                    Executors.newSingleThreadExecutor(),
                    applicationContext,
                    ClientConfig().also { it.packageName = packageName },
                ),
                this,
            )
        }
        Shared.authService.pushNotificationReceived(push)
    }
}
```

**Comment by jedi1150** [comment]
When an incoming push notification is received, `AudioCallApplication.onCreate()` is called first, where `authService` is initialized, then `FirebasePushService.onMessageReceived()` is called. So there shouldn't be an issue here.

Please clarify if you had a problem? Can you share more details about the problem?

What do you mean by killed app? Did you swipe it off the Recents screen or was the app force-stopped?

**Comment by jedi1150** [comment]
Issue closed due to no response. If the issue persists, please reopen.
