### ISSUE TITLE
SelectAudio not working for SPEAKER

### ISSUE THREAD

**Issue by RuslanMusin** [voximplant/android-sdk-kotlin-demo#3]
Добрый день!
Возникла проблема с audioDeviceManager.selectAudioDevice(device)
В демо было бы неплохо добавить ограничение, которое указано у метода - нельзя выбрать EARPIECE, если есть WIRED. Точнее не делать EARPIECE available, если есть WIRED
Но я нашел возможный баг в другом случае.
Если подключить WIRED и BLUETOOTH, то при переходе с WIRED на SPEAKER переход выполняется
Но если перейти с BLUETOOTH на SPEAKER, то переход идет на WIRED
По логам voximplant sdk я увидел, что идет переход на SPEAKER, а потом на WIRED
Этот баг возникает на нескольких устройствах. Пока что для такого случая переключаю так: BLUETOOTH-SPEAKER(выходит WIRED)-SPEAKER (теперь уже SPEAKER). Но звук на секунду появляется в проводном.
Прошу вас рассмотреть этот случай и, если баг подтвердиться, поправить его.

**Comment by YuliaGrigorieva** [comment]
Добрый день @RuslanMusin ,

Благодарим за предоставленную информацию.
Мы смогли воспроизвести проблему на нашей стороне.

С уважением,
Юлия Григорьева

**Comment by RuslanMusin** [comment]
Добрый день @YuliaGrigorieva 

Хотел узнать, решена ли проблема в новых версиях?

**Comment by YuliaGrigorieva** [comment]
Добрый день!

Мы выпустили обновление Voximplant Android SDK 2.23.1 с решением для данной проблемы.

С уважением,
Юлия Григорьева
